name: Publish

on:
  push:
    tags:
      - '*@*.*.*'
    #branches:
    #  - main
  workflow_dispatch:

  #release:
    #types: [published]
    #tags:
    #  - *@v*.*.*

jobs:
  publish:
    if: github.ref == 'refs/heads/main' # run publish only for the main branch
    name: Publish
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    permissions:
      actions: read
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9.2.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - name: Print Environment Info
        run: npx nx report

      - name: build
        run: npx nx run-many -t build

      - name: Publish packages
        run: npx nx release publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
